development:
  # Django Required starting settings
  STATIC_ROOT: ./familytree/static/
  STATIC_URL: /static/
  DEBUG: True
  TEMPLATE_DEBUG: True
  ALLOWED_HOSTS:
    - '*'
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - debug_toolbar
    - familytree.apps.FamilytreeConfig
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
    - debug_toolbar.middleware.DebugToolbarMiddleware
  ROOT_URLCONF: fullstackpath.urls
  WSGI_APPLICATION: fullstackpath.wsgi.application
  LANGUAGE_CODE: en-us
  TIME_ZONE: UTC
  USE_I18N: true
  USE_L10N: true
  USE_TZ: true
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: []
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

  # Password validation
  # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  # Database
  # https://docs.djangoproject.com/en/2.0/ref/settings/#databases
  INTERNAL_IPS:
    - 127.0.0.1
    - localhost
  STATICFILES_FINDERS:
    - django.contrib.staticfiles.finders.AppDirectoriesFinder
  DEBUG_TOOLBAR_CONFIG:
    INSERT_BEFORE: </head>
  LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
      simple:
        format: '%(asctime)s - %(levelname)s - %(message)s'
    handlers:
      file:
        level: WARNING
        class: logging.FileHandler
        formatter: simple
        filename: C:\Users\Yaroslav\source\repos\DjangoTest\fullstackpath\fullstackpath\log.log
    loggers:
      familytree:
        handlers:       
          -  file
        level: WARNING
        propagate: True