# Generated by Django 3.1.1 on 2020-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=128)),
                ('person_surname', models.CharField(max_length=128)),
                ('person_age', models.IntegerField()),
                ('person_sex', models.CharField(max_length=10)),
                ('person_familystatus', models.CharField(max_length=10)),
                ('person_country', models.CharField(max_length=128)),
            ],
        ),
    ]
