# Generated by Django 3.1.1 on 2020-09-29 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familytree', '0002_auto_20200929_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='user',
        ),
        migrations.AlterField(
            model_name='parents',
            name='parent_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
