# Generated by Django 3.1.1 on 2020-10-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familytree', '0005_auto_20201004_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_parents',
            name='grand_parent_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grand_parents',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='parents',
            name='parent_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parents',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='sibling_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
