# Generated by Django 3.1.1 on 2020-10-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0007_auto_20201007_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='person_age',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_country',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_family_status',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_sex',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_surname',
        ),
    ]
