# Generated by Django 3.1.1 on 2020-10-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0014_grand_parents_parents_siblings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grand_parents',
            old_name='grand_parent_of',
            new_name='of_user',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='parent_of',
            new_name='of_user',
        ),
        migrations.RenameField(
            model_name='siblings',
            old_name='sibling_of',
            new_name='of_user',
        ),
    ]
