# Generated by Django 3.1.1 on 2020-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0016_spouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='of_user',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='of_user',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='of_user',
        ),
        migrations.DeleteModel(
            name='Grand_Parents',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
        migrations.DeleteModel(
            name='Siblings',
        ),
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
