# Generated by Django 3.1.1 on 2020-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0018_grand_parents_parents_siblings_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_parents',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='parents',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='person_family_status',
            field=models.CharField(choices=[('none', 'No information'), ('single', 'single'), ('engaged', 'engaged'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=10),
        ),
    ]
