# Generated by Django 3.1.1 on 2020-10-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0019_auto_20201020_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grand_parents',
            old_name='of_user',
            new_name='belongs_to_user',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='of_user',
            new_name='belongs_to_user',
        ),
        migrations.RenameField(
            model_name='siblings',
            old_name='of_user',
            new_name='belongs_to_user',
        ),
        migrations.RenameField(
            model_name='spouse',
            old_name='of_user',
            new_name='belongs_to_user',
        ),
    ]
