# Generated by Django 3.1.3 on 2020-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0020_auto_20201029_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grand_parents',
            name='person_age',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='person_age',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='person_age',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='person_age',
        ),
        migrations.AddField(
            model_name='grand_parents',
            name='person_birth_date',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='parents',
            name='person_birth_date',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='siblings',
            name='person_birth_date',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='spouse',
            name='person_birth_date',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
