# Generated by Django 3.1.3 on 2020-12-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0021_auto_20201206_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grand_parents',
            old_name='person_birth_date',
            new_name='person_birthdate',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='person_birth_date',
            new_name='person_birthdate',
        ),
        migrations.RenameField(
            model_name='siblings',
            old_name='person_birth_date',
            new_name='person_birthdate',
        ),
        migrations.RenameField(
            model_name='spouse',
            old_name='person_birth_date',
            new_name='person_birthdate',
        ),
    ]
