# Generated by Django 3.1.3 on 2020-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0022_auto_20201206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_parents',
            name='person_birthdate',
            field=models.DateField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='parents',
            name='person_birthdate',
            field=models.DateField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='person_birthdate',
            field=models.DateField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='person_birthdate',
            field=models.DateField(default=None, max_length=16),
        ),
    ]
