# Generated by Django 3.1.3 on 2020-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0023_auto_20201206_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_parents',
            name='person_family_status',
            field=models.CharField(choices=[['none', 'No information'], ['single', 'single'], ['engaged', 'engaged'], ['married', 'married'], ['divorced', 'divorced'], ['widowed', 'widowed']], max_length=10),
        ),
        migrations.AlterField(
            model_name='grand_parents',
            name='person_sex',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=12),
        ),
        migrations.AlterField(
            model_name='parents',
            name='person_family_status',
            field=models.CharField(choices=[['none', 'No information'], ['single', 'single'], ['engaged', 'engaged'], ['married', 'married'], ['divorced', 'divorced'], ['widowed', 'widowed']], max_length=10),
        ),
        migrations.AlterField(
            model_name='parents',
            name='person_sex',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=12),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='person_family_status',
            field=models.CharField(choices=[['none', 'No information'], ['single', 'single'], ['engaged', 'engaged'], ['married', 'married'], ['divorced', 'divorced'], ['widowed', 'widowed']], max_length=10),
        ),
        migrations.AlterField(
            model_name='siblings',
            name='person_sex',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=12),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='person_family_status',
            field=models.CharField(choices=[['none', 'No information'], ['single', 'single'], ['engaged', 'engaged'], ['married', 'married'], ['divorced', 'divorced'], ['widowed', 'widowed']], max_length=10),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='person_sex',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=12),
        ),
    ]
